### ISSUE TITLE
max-cores-per-job ignored

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/protect#101]
`ProTECT --config config2.txt --maxCores 25 --max-cores-per-job 10 --workDir ./workdir ./jobstore`
Dies with
`AssertionError: The job is requesting 80.0 cores, more than the maximum of 25 cores this batch system was configured with. Scale is set to 1.`
[log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.5)
[config](http://hgwdev.cse.ucsc.edu/~jeltje/toil/config2.txt)

It would be helpful if `--max-cores-per-job` was automatically set to `--maxCores` so you don't have to enter both options.

**Comment by arkal** [comment]
I see the issue. Simple fix. I'll push a patch asap.

> It would be helpful if --max-cores-per-job was automatically set to --maxCores so you don't have to enter both options.

If `--max-cores-per-job` is not specified, it should default to `--maxCores`
