### ISSUE TITLE
Cannot start container

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/protect#105]
Not sure whether this is a stacker system problem. I'm getting 12 versions of
```
System error: write /sys/fs/cgroup/devices/system.slice/docker-c21b508e6525a5352ff4ed859c09ae49227f731d6795d032071156eaea8ff726.scope/cgroup.procs: no such device
```
`protect (2.2.2a1.dev82)`
`ProTECT --config config3.txt --maxCores 25 --max-cores-per-job 10 --workDir /scratch/jeltje/protect/workdir /scratch/jeltje/protect/jobstore`
[log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/log.6)
[config](http://hgwdev.cse.ucsc.edu/~jeltje/toil/config3.txt)

**Comment by arkal** [comment]
not a protect error... If you google the error you will see this is a docker issue and crosbymichael on [this github issue](https://github.com/docker/docker/issues/17653#issuecomment-155609224) thread suggests a temporary fix

**Comment by Jeltje** [comment]
Thanks!
