### ISSUE TITLE
All CPUs in use despite --maxCores

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/protect#106]
`protect (2.2.2a1.dev82)`
I'm running on a fresh 32 core VM, with no other processes running. Before starting the process, one or two CPUs showed a few percent activity.

`ProTECT --config config5.txt --maxCores 25 --workDir /tmp/protect/workdir /tmp/protect/jobstore`  

From `htop` I see that **all** CPUs are in 100% use, and there are a lot of docker processes listed in the tree.

I also noticed that there's no `--cpuset-cpus` listed in the docker calls, though I don't know if that's the only way to limit them.
`docker run --rm=true -v /tmp/protect/workdir/toil-7c8b79f7-d8f8-4d36-817c-ae37e97aad69/tmpzaRFC7/cd3560d2-3e0a-49cc-b28d-4313524da4c6:/data --log-driver=none aarjunrao/cutadapt:latest -a AGATCGGAAGAG -A AGATCGGAAGAG -m 35 -o /data/rna_cutadapt_1.fastq.gz -p /data/rna_cutadapt_2.fastq.gz /data/rna_1.fastq.gz /data/rna_2.fastq.gz`

I'm not sure how to tell which process is running on which core, so let me know how to get more details.

Adding @jvivian  because we had similar issues with `rnaseq-cgl`

**Comment by arkal** [comment]
This is a Toil issue. Weird tho. Run it with logdebug and try to make sense of the logs using the timestamps as a reference!

**Comment by hannes-ucsc** [comment]
IIRC, the guarantee that maxCores makes is that the sum of all `cores=` requirements of all concurrently running jobs never exceeds the set value. So if maxCores is 2, there can be 1 job with cores=2, two jobs with cores=1 or 4 jobs with cores=.5 and so on. If those jobs are 'lying' about their cores requirement, for example by starting a tool that uses more cores than the job declares, you will see the behavior you are describing. Estimating the CPU usage of a tool isn't an exact science and 25 is pretty close to 32 so I would be ok with that discrepancy. If you were running with maxCores=2 and still saw all cores fully used, I'd be worried. In fact, do you want to try that?

Also, I think the `htop` utility can help you in gauging which of the processes are using the CPU and how many of them there are.

**Comment by arkal** [comment]
+1 for the idea about `--maxCores=2`

**Comment by Jeltje** [comment]
`htop` is nice if you want to take screenshots, it's not easy to output to file, at least not in full. However, `ps -eH -o uname,pid,ppid,psr,pcpu,pmem,ni,cmd` at regular intervals shows that the system indeed sticks to `--maxCores=2`... mostly.  

The persistent exception (so far, because ProTECT doesn't finish anytime soon if you run it on two cores only):
```
USER       PID  PPID PSR %CPU %MEM  NI CMD
root     29886 29862   4  195  2.0   0           /usr/local/bin/bwa mem -t 2 -v 1 /data/bwa_indexes/hg19 /data/dna_1.fastq.gz /data/dna_2.fastq.gz
root     31127 31103  20  195  2.0   0           /usr/local/bin/bwa mem -t 2 -v 1 /data/bwa_indexes/hg19 /data/dna_1.fastq.gz /data/dna_2.fastq.gz
```
I think this means that there are two jobs running, each taking ~200% of a processor. Correct?

**Comment by hannes-ucsc** [comment]
Not necessarily. It looks like two threads of the same process. Maybe the entire process' CPU is reported for each thread? I don't know `ps` enough to interpret this with certainty.

**Comment by Jeltje** [comment]
I restarted the run with `--maxCores 15` and it seems to stay within that.

False alarm.
