### ISSUE TITLE
Add support for https download links

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/protect#149]
Pipelines should be able to download files form https links (Redwood will probably give us signed https links).

**Comment by arkal** [comment]
depends on #154

**Comment by arkal** [comment]
Hey Akul, Make sure you rebase onto the current master before you continue ok? Let me know if you have any problems.

**Comment by akul-goyal** [comment]
Hey Arjun,

I think I was able to push the files to BD2K. I don't know if this was what
you wanted me to do (if not please let me know what you actually wanted
done) I have not yet tested anything but will come in and do it tomorrow.

Thank You,
Akul Goyal

**Comment by cket** [comment]
@akul-goyal Ill show you how to rebase tomorrow when you come in - more git fun :)

**Comment by arkal** [comment]
@akul look at `src/protect/test/unit/test_file_downloads.py` also.
