### ISSUE TITLE
Make STAR-Fusion indexes for all edge lengths

### ISSUE THREAD

**Issue by jpfeil** [BD2KGenomics/protect#189]
continues #92

**Comment by arkal** [comment]
Completed and tested. Indexes at
protect-data/hg{19,38}_references/star_with_fusion_{50,75,100,150,250,300}bp_readlen_indexes.tar.gz
protect-data/hg38_references/GRCh38.d1.vd1/star_with_fusion_{50,75,100,150,250,300}bp_readlen_indexes.tar.gz
