### ISSUE TITLE
Filename different in S3 vs wrapper.py

### ISSUE THREAD

**Issue by wshands** [BD2KGenomics/protect#228]
the filename in wrapper.py( https://github.com/BD2KGenomics/protect/blob/master/docker/wrapper.py)
is "gencode.<reference_gencode>.pc_transcripts.fa.tar.gz",
but the filename is S3 is gencode.v25.pc_transcripts_NOPARY.fa.tar.gz
So wrapper.py needs to change or the filename in S3 needs to change

**Comment by arkal** [comment]
We assume if a user knows enough to change those options, they know gencode names it's files as v<VERSION_NUMBER>. The regex at the bottong of wrapper.py (line 466) correctly replaces <reference_gencode> with v19 or v26 for hg19 and hg38 respectively

(ftp://ftp.sanger.ac.uk/pub/gencode/Gencode_human/release_26/gencode.v26.pc_transcripts.fa.gz)
