### ISSUE TITLE
Get a test set for the AACR workshop

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/protect#5]
I believe this bioproject contains freely available fastqs from a breast cancer patient along with Lymphoblastoid cell lines from the same patient (T/N) This might be helpful

http://www.ncbi.nlm.nih.gov/bioproject/PRJEB2210

This is the matched RNA. Not sure if it's unprotected or not
http://trace.ncbi.nlm.nih.gov/Traces/sra/?run=SRR925710

**Comment by jpfeil** [comment]
s3://pimmuno-test-data/CI_test_input/reads

**Comment by arkal** [comment]
Resolved in #52. Closing
