### ISSUE TITLE
Protect doesn't see config file

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/protect#59]
`commit dd9b4c7661de6e11e5af7dd0ea0d5304cc60b33e`

`ProTECT --config_file my_parameters.yaml /mnt/data`
gets
```
ParameterError: The config file was not found at specified location. Please verify and retry.
```
Also, for some reason the error is written to STDOUT instead of STDERR.

full output at http://hgwdev.cse.ucsc.edu/~jeltje/toil/protect.log

**Comment by arkal** [comment]
you need to provide the full path because new toil puts you into the worker sandbox during runtime

**Comment by arkal** [comment]
i'll point that out in the manual

**Comment by Jeltje** [comment]
Then you need to explain that in the manual

**Comment by Jeltje** [comment]
Great minds
