### ISSUE TITLE
Create mini-references for CI

### ISSUE THREAD

**Issue by arkal** [BD2KGenomics/protect#6]
Use only chr6 so we have ~20k genes, and the MHC

**Comment by arkal** [comment]
Depends on #5

**Comment by arkal** [comment]
store references at ```pimmuno-test-data/CI_test_input/references```

**Comment by jpfeil** [comment]
Make protect handle different reference index bases. For example, run_bwa should use something like bwa_index instead of hg19 as the idxbase.

**Comment by arkal** [comment]
good catch. they can default to hg19 but should be customizable.

**Comment by arkal** [comment]
I suggest a flag called index_prefix in universal_options

**Comment by jpfeil** [comment]
We could also loop over the files in the bwa_index directory and take the idxbase name from the bwt file.

**Comment by hannes-ucsc** [comment]
@jpfeil to test this

**Comment by arkal** [comment]
Resolved in #52. Closing
