### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/protect#62]
ProTECT exits with 
```
IOError: [Errno 28] No space left on device
ERROR:toil.worker:Exiting the worker because of a failed jobWrapper on host jeltje-tb
```
However, my filesystem is fine (jobstore and output are supposed to go to /mnt/data):
```
Filesystem      Size  Used Avail Use% Mounted on
udev             24G     0   24G   0% /dev
tmpfs           4.8G  247M  4.6G   6% /run
/dev/vda1        49G   19G   31G  38% /
tmpfs            24G     0   24G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            24G     0   24G   0% /sys/fs/cgroup
/dev/vdb1       2.0T  1.3T  554G  71% /mnt
tmpfs           4.8G     0  4.8G   0% /run/user/1000
```
There is a suspicious `Unable to acquire lock on /tmp/toil-0fb5cb74-48c9-408d-b0e5-5c3cf37cce33/cache-0fb5cb74-48c9-408d-b0e5-5c3cf37cce33/.cacheLock` so I'm wondering if this is docker being greedy?
Full log at http://hgwdev.cse.ucsc.edu/~jeltje/toil/protect.nospace

**Comment by arkal** [comment]
/tmp is on /dev/vda1 which only has 31GB free.
 Most of the aligners ask for 60GB each right now so you can't run.
I'm working on #4 right now to make it a little better.

For now, you can do something similar to what is in jenkins.sh
`mkdir -p /mnt/ephemeral/tmp && export TMPDIR=/mnt/ephemeral/tmp`

**Comment by Jeltje** [comment]
Also put it in the manual...
