### ISSUE TITLE
bwa index file not found

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/protect#63]
I checked, and `S3://cgl-protect-data/hg19_references/bwa_index.tar.gz` exists.
However, ProTECT throws this error:
`[E::bwa_idx_load] fail to locate the index files`
Full log at http://hgwdev.cse.ucsc.edu/~jeltje/toil/bwa.error
(note that the program is still running so the log doesn't end with an error)

**Comment by arkal** [comment]
Yeah weird.... I just saw that.... Looking into it

**Comment by arkal** [comment]
Can you add a full stack trace?

**Comment by Jeltje** [comment]
It is still running. The link above is all I have so far.

**Comment by arkal** [comment]
no worries. I've figured it out ad i'm working on it

**Comment by arkal** [comment]
I assume both your bwas finished successfully if you're complaining about muse. @Jeltje  can I close this?

**Comment by Jeltje** [comment]
Sure!
