### ISSUE TITLE
max-cores-per-job should not be mutually exclusive with config option

### ISSUE THREAD

**Issue by Jeltje** [BD2KGenomics/protect#95]
ProTECT usage statement:
```
usage: ProTECT [-h]
               (--config_file CONFIG_FILE | --max-cores-per-job MAX_CORES | --generate_config)
```
And indeed, when trying
`ProTECT --config config1.txt --workdir workdir --max-cores-per-job 5 /mnt/test_protect/jobstore`
The error is
`ProTECT: error: argument --max-cores-per-job: not allowed with argument --config_file`

**Comment by arkal** [comment]
stupid me. Will fix.
